# Optimized AMCL Configuration
# Frame IDs
odom_frame_id: odom
base_frame_id: base_link
global_frame_id: map

# Filter Parameters - More particles for better localization
min_particles: 500
max_particles: 2000
kld_err: 0.02
kld_z: 0.99

# Update frequencies - Higher for better tracking
odom_freq: 20.0
laser_max_beams: 120       # Use more laser beams for better accuracy

# Odometry model parameters - Tune based on your robot's accuracy
odom_model_type: diff
odom_alpha1: 0.1           # Rotation noise from rotation (reduce if odometry is good)
odom_alpha2: 0.1           # Rotation noise from translation
odom_alpha3: 0.1           # Translation noise from translation
odom_alpha4: 0.1           # Translation noise from rotation
odom_alpha5: 0.1           # Translation noise (strafe - for omni robots)

# Laser model parameters
laser_model_type: likelihood_field
laser_max_range: 12.0
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_z_hit: 0.95
laser_z_short: 0.1
laser_z_max: 0.05
laser_z_rand: 0.05

# Initial pose parameters
initial_pose_x: -1.0       # Match your spawn position
initial_pose_y: 1.0
initial_pose_a: 0.0
initial_cov_xx: 0.25
initial_cov_yy: 0.25
initial_cov_aa: 0.068

# Recovery parameters - Better recovery from localization failures
recovery_alpha_slow: 0.001
recovery_alpha_fast: 0.1

# Transform parameters
transform_tolerance: 0.2
gui_publish_rate: 10.0
save_pose_rate: 0.5

# Update parameters for better performance
update_min_d: 0.1          # Update after 10cm movement
update_min_a: 0.1          # Update after ~6 degree rotation