obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]
# Or use radius if circular:
# robot_radius: 0.2

inflation_radius: 0.5

observation_sources: scan
scan:
  sensor_frame: laser_link
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true
