# Common costmap parameters
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 2.0
resolution: 0.05

# Robot footprint - Adjust based on your robot size
footprint: [[-0.2, -0.15], [-0.2, 0.15], [0.2, 0.15], [0.2, -0.15]]
# Or use radius if circular: robot_radius: 0.2

# Layer configuration
plugins:
  - {name: static_layer,            type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

# Static layer (for map)
static_layer:
  enabled: true
  map_topic: /map

# Obstacle layer (for dynamic obstacles)
obstacle_layer:
  enabled: true
  observation_sources: scan
  scan:
    topic: /scan
    data_type: LaserScan
    clearing: true
    marking: true
    max_obstacle_height: 2.0
    min_obstacle_height: 0.0
    obstacle_range: 2.5      # How far to add obstacles
    raytrace_range: 3.0      # How far to clear obstacles
    inf_is_valid: false

# Inflation layer
inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0   # Higher = more conservative around obstacles
  inflation_radius: 0.35     # Should be > robot radius for safety