global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true
  rolling_window: false
  
  width: 13.8      # 276 pixels * 0.05 resolution
  height: 11.6     # 232 pixels * 0.05 resolution
  resolution: 0.05
  origin_x: -5.760373  # Exact match to your map origin
  origin_y: -5.775     # Exact match to your map origin